### ISSUE TITLE
Example for Fractional Abundance plot

### ISSUE THREAD

**Issue by aburousan** [vallima/PRyMordial#1]
I was reading the arxiv article. It is really great but I have a bit hard time understanding this.
So, I was wondering if you guys can add an example for plotting images like shown below?
![Screenshot from 2023-11-13 02-07-05](https://github.com/vallima/PRyMordial/assets/60939745/a5d49386-fe96-4d60-91ea-3911005f1784)
taken from baumann's book under BBN part (chapter 3 - page 119)

**Comment by vallima** [comment]
The code returns by default the yields at the end of BBN, but it should be easy to tweak it in order to get this plot ... I'll see what I can do with my spare time :)
